ThemeManager : Remove uneeded state changes
The saving/restoring in the incorrect state were causing :
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState

Change-Id: Icfc03e50e6a07ff672194b9e621c5e05797d9ef1